[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.21.0"
pydantic-settings = "^2.10.1"

[tool.poetry.group.black.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
flake8 = "^7.3.0"

